version: '2'
services:
    ykcrf-app:
        image: ykcrf
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ykcrf-mysql:3306/ykcrf?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ykcrf-mysql:
        extends:
            file: mysql.yml
            service: ykcrf-mysql
